github.com:
    users:
        jonathanabner15-source:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: jonathanabner15-source
